"""
seed_data.py — Default graph datasets loaded into MongoDB on first run.
"""

SEED_DATASETS: dict[str, dict] = {
    "movies": {
        "name": "Movies & Actors",
        "description": "Iconic films and the people who made them",
        "nodes": [
            {"id": "n1",  "label": "Movie",  "name": "The Matrix",             "desc": "1999 sci-fi by the Wachowskis"},
            {"id": "n2",  "label": "Movie",  "name": "Inception",              "desc": "2010 thriller by Christopher Nolan"},
            {"id": "n3",  "label": "Movie",  "name": "Interstellar",           "desc": "2014 space epic by Christopher Nolan"},
            {"id": "n4",  "label": "Movie",  "name": "John Wick",              "desc": "2014 action thriller"},
            {"id": "n5",  "label": "Movie",  "name": "Tenet",                  "desc": "2020 time-inversion thriller"},
            {"id": "n6",  "label": "Person", "name": "Keanu Reeves",           "desc": "Canadian actor, born 1964"},
            {"id": "n7",  "label": "Person", "name": "Leonardo DiCaprio",      "desc": "American actor and producer"},
            {"id": "n8",  "label": "Person", "name": "Christopher Nolan",      "desc": "British-American film director"},
            {"id": "n9",  "label": "Person", "name": "Lana Wachowski",         "desc": "American film director"},
            {"id": "n10", "label": "Person", "name": "Matthew McConaughey",    "desc": "American actor"},
            {"id": "n11", "label": "Person", "name": "John David Washington",  "desc": "American actor"},
            {"id": "n12", "label": "Genre",  "name": "Sci-Fi",                 "desc": "Science fiction genre"},
            {"id": "n13", "label": "Genre",  "name": "Action",                 "desc": "Action genre"},
        ],
        "edges": [
            {"id": "e1",  "source": "n6",  "target": "n1",  "type": "ACTED_IN"},
            {"id": "e2",  "source": "n9",  "target": "n1",  "type": "DIRECTED"},
            {"id": "e3",  "source": "n7",  "target": "n2",  "type": "ACTED_IN"},
            {"id": "e4",  "source": "n8",  "target": "n2",  "type": "DIRECTED"},
            {"id": "e5",  "source": "n8",  "target": "n3",  "type": "DIRECTED"},
            {"id": "e6",  "source": "n10", "target": "n3",  "type": "ACTED_IN"},
            {"id": "e7",  "source": "n8",  "target": "n5",  "type": "DIRECTED"},
            {"id": "e8",  "source": "n11", "target": "n5",  "type": "ACTED_IN"},
            {"id": "e9",  "source": "n6",  "target": "n4",  "type": "ACTED_IN"},
            {"id": "e10", "source": "n1",  "target": "n12", "type": "IN_GENRE"},
            {"id": "e11", "source": "n2",  "target": "n12", "type": "IN_GENRE"},
            {"id": "e12", "source": "n3",  "target": "n12", "type": "IN_GENRE"},
            {"id": "e13", "source": "n4",  "target": "n13", "type": "IN_GENRE"},
            {"id": "e14", "source": "n5",  "target": "n12", "type": "IN_GENRE"},
        ],
    },

    "tech": {
        "name": "Tech Companies",
        "description": "Silicon Valley founders, companies and products",
        "nodes": [
            {"id": "t1",  "label": "Company",  "name": "Apple",           "desc": "Consumer electronics giant, founded 1976"},
            {"id": "t2",  "label": "Company",  "name": "Tesla",           "desc": "Electric vehicles & clean energy"},
            {"id": "t3",  "label": "Company",  "name": "SpaceX",          "desc": "Aerospace manufacturer & space transport"},
            {"id": "t4",  "label": "Company",  "name": "OpenAI",          "desc": "AI safety and research laboratory"},
            {"id": "t5",  "label": "Company",  "name": "Google",          "desc": "Technology conglomerate, Alphabet subsidiary"},
            {"id": "t6",  "label": "Company",  "name": "Microsoft",       "desc": "Software, cloud and AI giant"},
            {"id": "t7",  "label": "Person",   "name": "Elon Musk",       "desc": "CEO of Tesla & SpaceX, CTO of X"},
            {"id": "t8",  "label": "Person",   "name": "Steve Jobs",      "desc": "Co-founder of Apple, Pixar"},
            {"id": "t9",  "label": "Person",   "name": "Sam Altman",      "desc": "CEO of OpenAI"},
            {"id": "t10", "label": "Person",   "name": "Sundar Pichai",   "desc": "CEO of Google & Alphabet"},
            {"id": "t11", "label": "Product",  "name": "iPhone",          "desc": "Flagship smartphone by Apple"},
            {"id": "t12", "label": "Product",  "name": "GPT-4",           "desc": "Large language model by OpenAI"},
            {"id": "t13", "label": "Location", "name": "Silicon Valley",  "desc": "Technology hub in California, USA"},
        ],
        "edges": [
            {"id": "te1",  "source": "t7",  "target": "t2",  "type": "FOUNDED"},
            {"id": "te2",  "source": "t7",  "target": "t3",  "type": "FOUNDED"},
            {"id": "te3",  "source": "t8",  "target": "t1",  "type": "FOUNDED"},
            {"id": "te4",  "source": "t9",  "target": "t4",  "type": "LEADS"},
            {"id": "te5",  "source": "t10", "target": "t5",  "type": "LEADS"},
            {"id": "te6",  "source": "t1",  "target": "t11", "type": "MAKES"},
            {"id": "te7",  "source": "t4",  "target": "t12", "type": "CREATED"},
            {"id": "te8",  "source": "t1",  "target": "t13", "type": "LOCATED_IN"},
            {"id": "te9",  "source": "t5",  "target": "t13", "type": "LOCATED_IN"},
            {"id": "te10", "source": "t4",  "target": "t13", "type": "LOCATED_IN"},
            {"id": "te11", "source": "t6",  "target": "t4",  "type": "INVESTED_IN"},
            {"id": "te12", "source": "t5",  "target": "t6",  "type": "COMPETES_WITH"},
        ],
    },

    "science": {
        "name": "Scientific Minds",
        "description": "Physics, math and the minds behind them",
        "nodes": [
            {"id": "s1",  "label": "Person",  "name": "Albert Einstein",    "desc": "Theoretical physicist, Nobel 1921"},
            {"id": "s2",  "label": "Person",  "name": "Niels Bohr",         "desc": "Danish physicist, Nobel 1922"},
            {"id": "s3",  "label": "Person",  "name": "Marie Curie",        "desc": "Polish-French physicist, 2× Nobel"},
            {"id": "s4",  "label": "Person",  "name": "Isaac Newton",       "desc": "English mathematician & physicist"},
            {"id": "s5",  "label": "Person",  "name": "Richard Feynman",    "desc": "American theoretical physicist, Nobel 1965"},
            {"id": "s6",  "label": "Concept", "name": "Relativity",         "desc": "Einstein's theory of space-time curvature"},
            {"id": "s7",  "label": "Concept", "name": "Quantum Mechanics",  "desc": "Physics of atomic and subatomic scales"},
            {"id": "s8",  "label": "Concept", "name": "Radioactivity",      "desc": "Spontaneous nuclear decay of unstable atoms"},
            {"id": "s9",  "label": "Concept", "name": "Gravity",            "desc": "Fundamental attractive force between masses"},
            {"id": "s10", "label": "Concept", "name": "QED",                "desc": "Quantum electrodynamics — light-matter interaction"},
            {"id": "s11", "label": "Science", "name": "Physics",            "desc": "Natural science of matter, energy, space, time"},
            {"id": "s12", "label": "Science", "name": "Chemistry",          "desc": "Study of matter, its properties and reactions"},
        ],
        "edges": [
            {"id": "se1",  "source": "s1",  "target": "s6",  "type": "PROPOSED"},
            {"id": "se2",  "source": "s2",  "target": "s7",  "type": "CONTRIBUTED_TO"},
            {"id": "se3",  "source": "s1",  "target": "s7",  "type": "CONTRIBUTED_TO"},
            {"id": "se4",  "source": "s3",  "target": "s8",  "type": "DISCOVERED"},
            {"id": "se5",  "source": "s4",  "target": "s9",  "type": "FORMULATED"},
            {"id": "se6",  "source": "s5",  "target": "s10", "type": "DEVELOPED"},
            {"id": "se7",  "source": "s1",  "target": "s11", "type": "STUDIED"},
            {"id": "se8",  "source": "s2",  "target": "s11", "type": "STUDIED"},
            {"id": "se9",  "source": "s3",  "target": "s12", "type": "STUDIED"},
            {"id": "se10", "source": "s6",  "target": "s11", "type": "FIELD"},
            {"id": "se11", "source": "s7",  "target": "s11", "type": "FIELD"},
            {"id": "se12", "source": "s1",  "target": "s2",  "type": "COLLABORATED_WITH"},
        ],
    },

    "graphmind": {
        "name": "GraphMind Schema",
        "description": "Architecture components of the GraphMind platform",
        "nodes": [
            {"id": "g1",  "label": "Concept",      "name": "GraphMind",         "desc": "Enterprise knowledge graph platform"},
            {"id": "g2",  "label": "Concept",      "name": "Index-Free Adj.",   "desc": "O(1) pointer-based traversal — no index scan"},
            {"id": "g3",  "label": "Concept",      "name": "Raft Consensus",    "desc": "Distributed replication & leader election"},
            {"id": "g4",  "label": "Concept",      "name": "HNSW Index",        "desc": "Hierarchical Navigable Small World vector index"},
            {"id": "g5",  "label": "Concept",      "name": "Cypher Engine",     "desc": "Graph query language processor"},
            {"id": "g6",  "label": "Concept",      "name": "NLP Pipeline",      "desc": "Named entity recognition & triple extraction"},
            {"id": "g7",  "label": "Concept",      "name": "Vertex-Cut Part.",  "desc": "Hub node replication for power-law graphs"},
            {"id": "g8",  "label": "Concept",      "name": "Entity Resolution", "desc": "Deduplication via embedding cosine similarity"},
            {"id": "g9",  "label": "Organization", "name": "Neo4j",             "desc": "Leading graph database company"},
            {"id": "g10", "label": "Organization", "name": "Google",            "desc": "Knowledge Graph pioneer — 500B+ facts"},
            {"id": "g11", "label": "Product",      "name": "RocksDB",           "desc": "Facebook's embedded KV storage engine"},
            {"id": "g12", "label": "Product",      "name": "Apache Kafka",      "desc": "Distributed event streaming platform"},
        ],
        "edges": [
            {"id": "ge1",  "source": "g1",  "target": "g2",  "type": "USES"},
            {"id": "ge2",  "source": "g1",  "target": "g3",  "type": "USES"},
            {"id": "ge3",  "source": "g1",  "target": "g4",  "type": "USES"},
            {"id": "ge4",  "source": "g1",  "target": "g5",  "type": "INCLUDES"},
            {"id": "ge5",  "source": "g1",  "target": "g6",  "type": "INCLUDES"},
            {"id": "ge6",  "source": "g1",  "target": "g7",  "type": "USES"},
            {"id": "ge7",  "source": "g6",  "target": "g8",  "type": "FEEDS_INTO"},
            {"id": "ge8",  "source": "g1",  "target": "g11", "type": "BUILT_ON"},
            {"id": "ge9",  "source": "g1",  "target": "g12", "type": "BUILT_ON"},
            {"id": "ge10", "source": "g1",  "target": "g9",  "type": "INSPIRED_BY"},
            {"id": "ge11", "source": "g1",  "target": "g10", "type": "INSPIRED_BY"},
            {"id": "ge12", "source": "g9",  "target": "g2",  "type": "USES"},
        ],
    },
}
